(function () {
    'use strict';

    window.KABlogCatalog = [
        {
            slug: 'government-contracts-litigation-bangladesh.html',
            title: 'Government Contracts & Litigation in Bangladesh: Legal Rights, Remedies & Strategy',
            excerpt: 'A complete guide to government contracts and litigation in Bangladesh — Public Procurement Act 2006, PPR 2008, tender disputes, blacklisting challenges, payment recovery, and writ remedies for contractors.',
            category: 'Government Contracts',
            categorySlug: 'government-contracts',
            author: 'Adv. Mustafa Kamal Chowdhury',
            authorSlug: 'mustafa-kamal-chowdhury',
            date: '2026-02-10',
            image: 'https://images.unsplash.com/photo-1555848962-6e79363ec58f?w=800&h=450&fit=crop',
            tags: ['government contracts Bangladesh', 'public procurement Bangladesh', 'PPR 2008', 'tender dispute Bangladesh', 'blacklisting contractor Bangladesh', 'PPA 2006', 'writ petition government contract']
        },
        {
            slug: 'global-investment-citizenship-programs-bangladesh.html',
            title: 'Global Investment & Citizenship Programs: A Legal Guide for Bangladeshi Investors',
            excerpt: 'A complete legal guide to global investment and citizenship programmes for Bangladeshi investors — Golden Visa, CBI options, dual citizenship rules, Bangladesh Bank compliance, and NRB status planning.',
            category: 'Global Investment & Immigration',
            categorySlug: 'global-investment',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-02-09',
            image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&h=450&fit=crop',
            tags: ['citizenship by investment Bangladesh', 'Golden Visa Bangladesh', 'NRB investment Bangladesh', 'overseas investment Bangladesh', 'dual citizenship Bangladesh', 'investment immigration Bangladesh', 'second passport Bangladesh']
        },
        {
            slug: 'fraud-white-collar-crimes-bangladesh.html',
            title: 'Fraud and White Collar Crimes in Bangladesh: Legal Framework, Offences & Defence',
            excerpt: 'A complete guide to fraud and white collar crimes in Bangladesh — cheating, forgery, money laundering, corporate fraud, ACC investigations, and legal defence strategy.',
            category: 'White Collar Crime',
            categorySlug: 'white-collar-crime',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-02-08',
            image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop',
            tags: ['fraud Bangladesh', 'white collar crime Bangladesh', 'money laundering Bangladesh', 'ACC investigation Bangladesh', 'cheating Penal Code Bangladesh', 'corporate fraud Bangladesh', 'criminal breach of trust Bangladesh']
        },
        {
            slug: 'foreign-investment-law-bangladesh.html',
            title: 'Foreign Investment Law in Bangladesh: Rights, Incentives & Legal Framework',
            excerpt: 'A complete guide to foreign investment law in Bangladesh — BIDA registration, investment protections, repatriation rights, EPZ incentives, and legal strategy for foreign investors.',
            category: 'Foreign Investment',
            categorySlug: 'foreign-investment',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-02-07',
            image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=450&fit=crop',
            tags: ['foreign investment Bangladesh', 'BIDA Bangladesh', 'FPI Act 1980', 'investment law Bangladesh', 'repatriation Bangladesh', 'EPZ Bangladesh', 'foreign investor rights Bangladesh']
        },
        {
            slug: 'environmental-law-bangladesh.html',
            title: 'Environmental Law in Bangladesh: Regulations, Compliance & Legal Remedies',
            excerpt: 'A complete guide to Bangladesh’s environmental law framework — ECC requirements, EIA obligations, pollution standards, DoE enforcement, and legal remedies for businesses and investors.',
            category: 'Environmental Law',
            categorySlug: 'environmental-law',
            author: 'Adv. Mohammad Kabir',
            authorSlug: 'mohammad-kabir',
            date: '2026-02-06',
            image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=450&fit=crop',
            tags: ['environmental law Bangladesh', 'Environment Conservation Act 1995', 'EIA Bangladesh', 'environmental compliance Bangladesh', 'Environment Court Bangladesh', 'pollution law Bangladesh']
        },
        {
            slug: 'entertainment-media-litigation-bangladesh.html',
            title: 'Entertainment & Media Litigation in Bangladesh: Rights, Disputes & Legal Protection',
            excerpt: 'Copyright infringement, defamation, broadcasting regulation, digital content liability, and contract disputes in Bangladesh’s entertainment and media industries — explained.',
            category: 'Entertainment & Media Law',
            categorySlug: 'entertainment-media-law',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-02-05',
            image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&h=450&fit=crop',
            tags: ['entertainment law Bangladesh', 'media litigation Bangladesh', 'copyright law Bangladesh', 'defamation law Bangladesh', 'broadcasting law Bangladesh', 'digital media law Bangladesh']
        },
        {
            slug: 'arbitration-bangladesh.html',
            title: 'Domestic & International Arbitration in Bangladesh: Process, Framework & Legal Strategy',
            excerpt: 'A complete guide to domestic and international arbitration in Bangladesh — Arbitration Act 2001, New York Convention, enforcement of awards, and expert legal strategy for businesses and investors.',
            category: 'ADR',
            categorySlug: 'adr',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-02-04',
            image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&h=450&fit=crop',
            tags: ['arbitration Bangladesh', 'international arbitration Bangladesh', 'Arbitration Act 2001', 'commercial arbitration', 'enforcement of arbitral award', 'dispute resolution Bangladesh']
        },
        {
            slug: 'criminal-defense-prosecution-bangladesh.html',
            title: 'Criminal Defense & Prosecution in Bangladesh: Rights, Process & Legal Strategy',
            excerpt: 'Bail rights, FIR process, trial procedure, and criminal defense strategies explained for individuals and families in Bangladesh.',
            category: 'Criminal Law',
            categorySlug: 'criminal-law',
            author: 'Adv. Nasrin Akter',
            authorSlug: 'nasrin-akter',
            date: '2026-02-03',
            image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=450&fit=crop',
            tags: ['criminal defense', 'criminal prosecution Bangladesh', 'bail application Bangladesh', 'criminal trial Bangladesh', 'criminal lawyer Bangladesh']
        },
        {
            slug: 'contract-law-bangladesh.html',
            title: 'Contract Law in Bangladesh: Formation, Enforcement & Legal Remedies',
            excerpt: 'Contract formation, enforceability, breach remedies, and how to protect your contractual rights under the Contract Act 1872 in Bangladesh.',
            category: 'Contract Law',
            categorySlug: 'contract-law',
            author: 'Adv. Harun Rayhan',
            authorSlug: 'harun-rayhan',
            date: '2026-02-02',
            image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop',
            tags: ['contract law', 'breach of contract', 'contract act 1872', 'commercial contracts', 'specific performance']
        },
        {
            slug: 'constitutional-law-bangladesh.html',
            title: 'Constitutional Law in Bangladesh: Rights, Remedies & Writ Jurisdiction',
            excerpt: 'Fundamental rights, writ petitions, judicial review, and constitutional remedies explained for citizens and businesses in Bangladesh.',
            category: 'Constitutional Law',
            categorySlug: 'constitutional-law',
            author: 'Adv. Mustafa Kamal Chowdhury',
            authorSlug: 'mustafa-kamal-chowdhury',
            date: '2026-02-01',
            image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=450&fit=crop',
            tags: ['constitutional law', 'fundamental rights', 'writ petition', 'supreme court bangladesh', 'high court division']
        },
        {
            slug: 'company-formation-guide.html',
            title: 'Company Formation in Bangladesh: A Step-by-Step Legal Guide',
            excerpt: 'Entity structure, RJSC process, and compliance sequencing.',
            category: 'Company Formation',
            categorySlug: 'company-formation',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-01-10',
            image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&h=450&fit=crop',
            tags: ['company formation', 'rjsc', 'corporate compliance', 'incorporation']
        },
        {
            slug: 'commercial-litigation-complete-guide.html',
            title: 'Commercial Litigation in Bangladesh: A Complete Guide',
            excerpt: 'Contract claims, injunctions, and evidence strategy.',
            category: 'Commercial Litigation',
            categorySlug: 'commercial-litigation',
            author: 'Adv. Mohammad Kabir',
            authorSlug: 'mohammad-kabir',
            date: '2026-01-09',
            image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=450&fit=crop',
            tags: ['commercial litigation', 'contracts', 'injunction', 'shareholder dispute']
        },
        {
            slug: 'civil-litigation-complete-guide.html',
            title: 'Civil Litigation in Bangladesh: A Complete Guide',
            excerpt: 'Procedure, injunctions, and decree enforcement essentials.',
            category: 'Civil Litigation',
            categorySlug: 'civil-litigation',
            author: 'Adv. Mohammad Kabir',
            authorSlug: 'mohammad-kabir',
            date: '2026-01-08',
            image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=450&fit=crop',
            tags: ['civil litigation', 'decree', 'court procedure', 'property claim']
        },
        {
            slug: 'business-setup-bangladesh.html',
            title: 'Business Setup in Bangladesh: A Complete Legal Guide',
            excerpt: 'Entity planning, registration flow, and launch compliance.',
            category: 'Business Setup',
            categorySlug: 'business-setup',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-01-07',
            image: 'https://images.unsplash.com/photo-1462899006636-339e08d1844e?w=800&h=450&fit=crop',
            tags: ['business setup', 'investment', 'rjsc', 'trade license']
        },
        {
            slug: 'banking-litigation-comprehensive.html',
            title: 'Banking Litigation in Bangladesh: A Comprehensive Guide',
            excerpt: 'Artha Rin defense, cheque disputes, and recovery strategy.',
            category: 'Banking Litigation',
            categorySlug: 'banking-litigation',
            author: 'Adv. Mustafa Kamal Chowdhury',
            authorSlug: 'mustafa-kamal-chowdhury',
            date: '2026-01-06',
            image: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=800&h=450&fit=crop',
            tags: ['banking litigation', 'artha rin', 'loan recovery', 'cheque dishonour']
        },
        {
            slug: 'banking-litigation-guide.html',
            title: 'Banking Litigation in Bangladesh: A Complete Legal Guide',
            excerpt: 'Debt recovery and borrower defense practical framework.',
            category: 'Banking Litigation',
            categorySlug: 'banking-litigation',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-01-05',
            image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&h=450&fit=crop',
            tags: ['banking litigation', 'debt recovery', 'borrower defense', 'finance disputes']
        },
        {
            slug: 'aviation-law-bangladesh.html',
            title: 'Aviation Law in Bangladesh: Navigating Complex Skies',
            excerpt: 'Regulation, operation, and liability for aviation sector.',
            category: 'Aviation Law',
            categorySlug: 'aviation-law',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-01-04',
            image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&h=450&fit=crop',
            tags: ['aviation law', 'aircraft regulation', 'airline liability', 'civil aviation']
        },
        {
            slug: 'adr-dispute-resolution.html',
            title: 'Alternative Dispute Resolution (ADR) in Bangladesh',
            excerpt: 'Mediation, arbitration, and faster dispute pathways.',
            category: 'ADR',
            categorySlug: 'adr',
            author: 'Adv. Nasrin Akter',
            authorSlug: 'nasrin-akter',
            date: '2026-01-03',
            image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&h=450&fit=crop',
            tags: ['adr', 'mediation', 'arbitration', 'negotiation']
        },
        {
            slug: 'admiralty-shipping-law.html',
            title: 'Admiralty & Shipping Law in Bangladesh',
            excerpt: 'Maritime contracts, cargo disputes, and vessel liability.',
            category: 'Admiralty & Shipping',
            categorySlug: 'admiralty-shipping',
            author: 'Adv. Harun Rayhan',
            authorSlug: 'harun-rayhan',
            date: '2026-01-02',
            image: 'https://images.unsplash.com/photo-1545243424-0ce743321e11?w=800&h=450&fit=crop',
            tags: ['admiralty law', 'shipping law', 'cargo dispute', 'maritime contracts']
        },
        {
            slug: 'administrative-law-bangladesh.html',
            title: 'Administrative Law in Bangladesh: Complete Legal Guide',
            excerpt: 'Writ remedies, due process, and public law accountability.',
            category: 'Administrative Law',
            categorySlug: 'administrative-law',
            author: 'Adv. Mohammad Mostofa Kamal',
            authorSlug: 'mohammad-mostofa-kamal',
            date: '2026-01-01',
            image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=450&fit=crop',
            tags: ['administrative law', 'writ petition', 'government decisions', 'judicial review']
        }
    ];
})();
